### ISSUE TITLE
Copyright Notice

### ISSUE THREAD

**Issue by zekroTJA** [archroid/ElProfessorBot#2]
Hey, I noticed you are using some of my packages (ken, dgrs and shireikan) in this repository. After some further examination, I noticed that you are also directly using some of the sources of my project shinpuru. For example:
 - https://github.com/archroid/ElProfessorBot/blob/main/commands/cmdclear.go
 - https://github.com/archroid/ElProfessorBot/blob/main/inits/commandhandler.go
 - https://github.com/archroid/ElProfessorBot/blob/main/inits/slashcommandhandler.go
 - https://github.com/archroid/ElProfessorBot/blob/main/pkg/acceptmsg/acceptmsg.go
 - https://github.com/archroid/ElProfessorBot/blob/main/pkg/embedbuilder/embedbuilder.go
 - https://github.com/archroid/ElProfessorBot/blob/main/pkg/fetch/fetch.go
 - https://github.com/archroid/ElProfessorBot/blob/main/utils/discordutils.go
 - https://github.com/archroid/ElProfessorBot/blob/main/utils/embeds.go
 - https://github.com/archroid/ElProfessorBot/blob/main/utils/utils.go
 - https://github.com/archroid/ElProfessorBot/blob/main/main.go

Especially the packages at `pkg` are direct copies of the public packages of shinpuru.

Because shinpuru is licensed under the [MIT License](https://github.com/zekroTJA/shinpuru/blob/master/LICENCE), you must provide copyright notice in distributions of your bot as long as you are using my sources.

It is completely fine that you are using my code, but it would be nice if you could add a copyright notice to your Readme and maybe also to the info page of your bot.

Tank you in advance.

**Comment by archroid** [comment]
Yeah thanks for your notice. I will add the copywrite notice. Thanks again for your friendly warning.
